### ISSUE TITLE
Implicit MP3 parameters

### ISSUE THREAD

**Issue by ThomasHezard** [Mercandj/audio-samples#1]
https://github.com/Mercandj/audio-samples/blob/866deecc36a769ca898b407dbfee5e88221bbae4/create_audio_samples.sh#L29

Careful, on this line, you end up with a 48kHz mp3 only because mp3 doesn't support 96 kHz sample rates. If your input file is 44,1kHz, there won't be any conversion.

Moreover, you don't specify which encoder you want to use (I think default is lame for MP3).

You should add every parameter you want to control explicitely : 
```
ffmpeg -i ./sample_bee_moved_96_khz_24_bit.flac -c:a libmp3lame -ar 44100 -ab 320k -map_metadata 0 -id3v2_version 3 ./build/sample_bee_moved_48_khz.mp3
```

**Comment by Mercandj** [comment]
Thks a lot!
I pushed your parameters here https://github.com/Mercandj/audio-samples/commit/e722daa736b288fc77b0b32d7e227e215d5be995
